# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Authen-Class-HtAuth
version:      0.01
version_from: lib/Authen/Class/HtAuth.pm
installdirs:  site
requires:
    Apache::Htgroup:               0
    Apache::Htpasswd:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
